[package]
name = "tiny4linux_assets"
version = "1.0.0"
edition = "2024"

include = [
    "Cargo.toml",
    "src/**",
    "generated/**"
]

[dependencies]
iced = {version = "0.14.0", default-features = false, features = ["image", "tiny-skia", "wgpu"]}
once_cell = "1.21.3"
